/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package HistoriaJogo;

public class App {
    public static void main(String[] args) {
        JogoAventura.main(args); // Chama diretamente o método main da classe JogoAventura
    }
}


